//! Generates the embedded asset-pack table for wasm (#108).
//!
//! Scans `game/assets` and writes `$OUT_DIR/embedded_pack.rs`: a
//! `GAME_ASSETS` table of `(pack-relative path, include_bytes!(..))` entries,
//! included by `src/lib.rs` under `cfg(target_arch = "wasm32")` and handed to
//! the runtime via `GameConfig::embedded_packs`. Generating the table (instead
//! of hand-listing files like the runtime's std-assets embed) means new
//! scenes/assets are picked up by the next build automatically.
//!
//! The generated entries use `concat!(env!("CARGO_MANIFEST_DIR"), ..)` rather
//! than baked absolute paths, so the file is machine-independent; dotfiles
//! (`.DS_Store` and friends) are skipped. Paths are pack-relative with forward
//! slashes to match the VFS request paths.
//!
//! On Windows the script also embeds the game icon + version resource
//! (`game/icon/icon.ico`, #133) via `winresource`. The dependency and the
//! code are gated on a *Windows host* — cargo resolves target-specific
//! build-dependencies against the host platform, and the realistic packaging
//! path is building on Windows for Windows.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=assets");

    emit_git_hash();

    #[cfg(windows)]
    embed_windows_resources();

    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let pack_root = Path::new(&manifest).join("assets");
    let mut paths = Vec::new();
    collect(&pack_root, String::new(), &mut paths);
    paths.sort();

    let mut out = String::from(
        "/// Every file in `game/assets`, verbatim (generated by build.rs).\n\
         pub static GAME_ASSETS: redlilium_runtime::EmbeddedPack = &[\n",
    );
    for path in &paths {
        writeln!(
            out,
            "    ({path:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/{path}\"))),"
        )
        .expect("write to String");
    }
    out.push_str("];\n");

    let out_path = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_pack.rs");
    std::fs::write(&out_path, out).expect("write embedded_pack.rs");
}

/// Build stamping (#135): expose the git commit as `CAR_GAME_GIT_HASH` so the
/// binary can identify itself in bug reports (`car_game::BUILD_STAMP`). A
/// `-dirty` suffix marks uncommitted changes; without git (source tarball)
/// the stamp degrades to "unknown". Caveat: cargo reruns this script on
/// HEAD/ref changes, so the dirty flag can lag edits that don't touch
/// otherwise-watched files — good enough for identifying builds.
fn emit_git_hash() {
    println!("cargo::rerun-if-changed=../.git/HEAD");
    println!("cargo::rerun-if-changed=../.git/refs");
    let git = |args: &[&str]| {
        std::process::Command::new("git")
            .args(args)
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
    };
    let hash = match git(&["rev-parse", "--short=9", "HEAD"]) {
        Some(hash) => {
            let dirty = git(&["status", "--porcelain", "--untracked-files=no"])
                .is_none_or(|s| !s.is_empty());
            if dirty { format!("{hash}-dirty") } else { hash }
        }
        None => "unknown".to_string(),
    };
    println!("cargo::rustc-env=CAR_GAME_GIT_HASH={hash}");
}

/// Embed the game icon and a version resource into the Windows executable
/// (#133). Skipped for non-Windows *targets* (e.g. a wasm build on a Windows
/// host) — resources are a PE concept.
#[cfg(windows)]
fn embed_windows_resources() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    println!("cargo::rerun-if-changed=icon/icon.ico");
    let mut res = winresource::WindowsResource::new();
    res.set_icon("icon/icon.ico");
    res.set("ProductName", "Car Game");
    res.set("FileDescription", "Car Game (RedLilium engine)");
    if let Err(e) = res.compile() {
        println!("cargo::warning=embedding Windows resources failed: {e}");
    }
}

/// Collect pack-relative (forward-slash) paths of every non-dotfile under `dir`.
fn collect(dir: &Path, prefix: String, paths: &mut Vec<String>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) => panic!("reading {dir:?}: {e}"),
    };
    for entry in entries {
        let entry = entry.expect("dir entry");
        let name = entry.file_name();
        let name = name.to_str().expect("asset file names are UTF-8");
        if name.starts_with('.') {
            continue;
        }
        let rel = if prefix.is_empty() {
            name.to_string()
        } else {
            format!("{prefix}/{name}")
        };
        if entry.file_type().expect("file type").is_dir() {
            collect(&entry.path(), rel, paths);
        } else {
            paths.push(rel);
        }
    }
}
