//! Generates the embedded asset-pack table for wasm (#108).
//!
//! Scans `game/assets` and writes `$OUT_DIR/embedded_pack.rs`: a
//! `GAME_ASSETS` table of `(pack-relative path, include_bytes!(..))` entries,
//! included by `src/lib.rs` under `cfg(target_arch = "wasm32")` and handed to
//! the runtime via `GameConfig::embedded_packs`. Generating the table (instead
//! of hand-listing files like the runtime's std-assets embed) means new
//! scenes/assets are picked up by the next build automatically.
//!
//! The generated entries use `concat!(env!("CARGO_MANIFEST_DIR"), ..)` rather
//! than baked absolute paths, so the file is machine-independent; dotfiles
//! (`.DS_Store` and friends) are skipped. Paths are pack-relative with forward
//! slashes to match the VFS request paths.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo::rerun-if-changed=assets");

    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let pack_root = Path::new(&manifest).join("assets");
    let mut paths = Vec::new();
    collect(&pack_root, String::new(), &mut paths);
    paths.sort();

    let mut out = String::from(
        "/// Every file in `game/assets`, verbatim (generated by build.rs).\n\
         pub static GAME_ASSETS: redlilium_runtime::EmbeddedPack = &[\n",
    );
    for path in &paths {
        writeln!(
            out,
            "    ({path:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/{path}\"))),"
        )
        .expect("write to String");
    }
    out.push_str("];\n");

    let out_path = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_pack.rs");
    std::fs::write(&out_path, out).expect("write embedded_pack.rs");
}

/// Collect pack-relative (forward-slash) paths of every non-dotfile under `dir`.
fn collect(dir: &Path, prefix: String, paths: &mut Vec<String>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) => panic!("reading {dir:?}: {e}"),
    };
    for entry in entries {
        let entry = entry.expect("dir entry");
        let name = entry.file_name();
        let name = name.to_str().expect("asset file names are UTF-8");
        if name.starts_with('.') {
            continue;
        }
        let rel = if prefix.is_empty() {
            name.to_string()
        } else {
            format!("{prefix}/{name}")
        };
        if entry.file_type().expect("file type").is_dir() {
            collect(&entry.path(), rel, paths);
        } else {
            paths.push(rel);
        }
    }
}
