//! # Car Game
//!
//! The arcade-car vertical slice (milestone "Vertical Slice — Arcade Car"):
//! game code authored as a [`redlilium_runtime::Plugin`], built both as a
//! standalone binary (`cargo run -p car-game`) and as a cdylib the editor's
//! `GameHost` can load and warm-restart-reload (#45).
//!
//! Gameplay (#104): a rapier-backed box chassis driven by WASD through
//! impulses (arcade model — no wheel joints), followed by a smoothed
//! third-person camera. The level is a placeholder until #105. The dev HUD
//! exercises the in-game UI layer (#100): an egui window drawn from a game
//! system through [`GameUi`], with a Quit button driving [`AppControl`].
#![recursion_limit = "256"]

use std::collections::VecDeque;
use std::f32::consts::FRAC_PI_4;

use redlilium_assets::Guid;
use redlilium_core::input::KeyCode;
use redlilium_core::math::{Quat, Vec3, nalgebra};
use redlilium_ecs::physics::components3d::{Collider3D, RigidBody3D};
use redlilium_ecs::physics::physics3d::{PhysicsWorld3D, RigidBody3DHandle};
use redlilium_ecs::physics::systems3d::{
    InterpolatePhysics, RecordPhysicsPose, StepPhysics3D, SyncPhysicsBodies3D,
};
use redlilium_ecs::{
    Camera, CameraAutoExposure, CameraBloom, Component, DirectionalLight, Entity, ExclusiveSystem,
    GlobalTransform, MaterialInstanceSource, MeshGenerator, MeshRenderer, MeshSource, Name,
    PostUpdate, Primitive, RawFrameDelta, Read, Res, ResMut, SceneManager, System, SystemContext,
    SystemError, Time, Transform, Update, UpdateGlobalTransforms, Visibility, WindowInput, World,
    WriteAll,
};
use redlilium_runtime::{App, GameUi, Plugin};
// The Quit button is native-only (a browser tab has no "exit").
#[cfg(not(target_arch = "wasm32"))]
use redlilium_runtime::AppControl;

/// Scene asset paths (mount-relative; generated by the `gen_scenes` bin until
/// the editor persists scenes, #2).
pub const MENU_SCENE: &str = "scenes/menu.scene";
pub const LEVEL_SCENE: &str = "scenes/level1.scene";
pub const PLAYGROUND_SCENE: &str = "scenes/levels_playground.scene";

/// Build stamp (#135): crate version + git commit, e.g. `0.1.0+1a2b3c4d5`
/// (`-dirty` marks uncommitted changes, `unknown` a git-less build). Printed
/// at startup and by `xtask dist` — identifies the build behind a bug report.
pub const BUILD_STAMP: &str = concat!(env!("CARGO_PKG_VERSION"), "+", env!("CAR_GAME_GIT_HASH"));

/// Rapier's public math vector (glam `DVec3` in the f64 build).
type PhysVector = redlilium_ecs::physics::rapier3d::prelude::Vector;

/// Arcade drive parameters, attached to the chassis entity.
#[derive(Clone, Component)]
pub struct CarController {
    /// Forward drive force, Newtons (mass ~ collider density × volume).
    pub engine_force: f32,
    /// Yaw steering torque, N·m.
    pub steer_torque: f32,
    /// Forward speed above which the engine stops adding force, m/s.
    pub max_speed: f32,
}

impl Default for CarController {
    fn default() -> Self {
        Self {
            engine_force: 700.0,
            steer_torque: 160.0,
            max_speed: 18.0,
        }
    }
}

/// Third-person follow parameters, attached to the camera entity. The target
/// is the (single) [`CarController`] entity.
#[derive(Clone, Component)]
pub struct FollowCamera {
    /// Distance behind the car, meters.
    pub distance: f32,
    /// Height above the car, meters.
    pub height: f32,
    /// Exponential smoothing rate (higher = stiffer), 1/s.
    pub stiffness: f32,
}

impl Default for FollowCamera {
    fn default() -> Self {
        Self {
            distance: 7.0,
            height: 3.0,
            stiffness: 6.0,
        }
    }
}

/// Marks the car spawn point in a level scene (#105). The scene asset carries
/// the marker (authorable in the editor like any other component); once the
/// scene is instantiated, [`SpawnCarAtMarkers`] materializes the drivable
/// chassis at the marker's `Transform`.
#[derive(Debug, Clone, Copy, Default, Component)]
pub struct CarSpawn;

/// Local forward of the chassis model. The visual box is long along Z and the
/// camera convention is -Z forward, so the car drives toward -Z.
const CAR_FORWARD: PhysVector = PhysVector::new(0.0, 0.0, -1.0);

/// How aggressively lateral (sideways) velocity is damped, 1/s. This is the
/// arcade stand-in for tire grip: the chassis collider is near-frictionless
/// (a sliding box would otherwise need engine force to beat µmg), and this
/// redirect makes the car go where its nose points instead of drifting.
const LATERAL_GRIP: f64 = 6.0;

/// Fixed sub-step the follow camera integrates its smoothing with, seconds.
///
/// The camera must not inherit the frame rate: an exponential blend chasing a
/// *moving* target settles at a lag of `v*dt / (1 - exp(-k*dt))`, which grows
/// with `dt`, so stepping it once per frame makes the trailing distance vary
/// with frame time. Integrating in fixed sub-steps makes the lag a property of
/// this constant instead — the camera behaves identically at any frame rate.
const CAMERA_SMOOTHING_STEP: f32 = 1.0 / 120.0;

/// WASD arcade drive (#104): apply engine/steering impulses to the chassis
/// body. No joints or wheels — forces on a single rigid body, tuned for feel,
/// with steering authority scaled by speed (a parked car does not yaw).
pub struct DriveCar;

impl System for DriveCar {
    type Result = ();
    fn run<'a>(&'a self, ctx: &'a SystemContext<'a>) -> Result<(), SystemError> {
        ctx.lock::<(
            Res<Time>,
            Res<WindowInput>,
            ResMut<PhysicsWorld3D>,
            Read<CarController>,
            Read<RigidBody3DHandle>,
        )>()
        .execute(|(time, input, mut physics, cars, handles)| {
            if input.ui_wants_input {
                return;
            }
            let dt = time.delta();
            let throttle = (input.is_key_pressed(KeyCode::W) as i8
                - input.is_key_pressed(KeyCode::S) as i8) as f64;
            let steer = (input.is_key_pressed(KeyCode::A) as i8
                - input.is_key_pressed(KeyCode::D) as i8) as f64;

            for (idx, car) in cars.iter() {
                let Some(handle) = handles.get(idx) else {
                    continue;
                };
                let Some(body) = physics.bodies.get_mut(handle.0) else {
                    continue;
                };
                let forward = body.rotation() * CAR_FORWARD;
                let forward_speed = body.linvel().dot(forward);

                if throttle != 0.0 && forward_speed.abs() < car.max_speed as f64 {
                    let impulse = forward * (throttle * car.engine_force as f64 * dt);
                    body.apply_impulse(impulse, true);
                }
                if steer != 0.0 {
                    // Steering authority grows with speed and flips in
                    // reverse, like a real steered axle.
                    let authority = (forward_speed.abs() / 3.0).min(1.0)
                        * if forward_speed < -0.5 { -1.0 } else { 1.0 };
                    let impulse = steer * car.steer_torque as f64 * authority * dt;
                    body.apply_torque_impulse(PhysVector::new(0.0, impulse, 0.0), true);
                }

                // Tire grip: bleed off sideways velocity so the car follows
                // its nose. Y is left alone (gravity/jumps).
                let velocity = body.linvel();
                let forward_speed = velocity.dot(forward);
                let lateral = velocity - forward * forward_speed;
                let lateral_xz = PhysVector::new(lateral.x, 0.0, lateral.z);
                let bleed = 1.0 - (-LATERAL_GRIP * dt).exp();
                body.set_linvel(velocity - lateral_xz * bleed, true);
            }
        });
        Ok(())
    }
}

/// Places the [`FollowCamera`] behind its [`CarController`] target with
/// exponential smoothing. Runs in `PostUpdate` before transform propagation,
/// reading the chassis pose [`StepPhysics3D`] wrote during `FixedUpdate`
/// (which runs earlier in the same frame, so the pose is this frame's latest).
pub struct UpdateFollowCamera;

impl System for UpdateFollowCamera {
    type Result = ();
    fn run<'a>(&'a self, ctx: &'a SystemContext<'a>) -> Result<(), SystemError> {
        ctx.lock::<(
            Res<Time>,
            Read<CarController>,
            Read<FollowCamera>,
            WriteAll<Transform>,
        )>()
        .execute(|(time, cars, followers, mut transforms)| {
            let Some((car_idx, _)) = cars.iter().next() else {
                return;
            };
            let Some(car_transform) = transforms.get(car_idx).copied() else {
                return;
            };
            let car_pos = car_transform.translation;
            // Flatten the car's forward onto XZ so camera height never chases
            // chassis pitch (ramp hops stay readable).
            let forward3 = redlilium_core::math::quat_rotate_vec3(
                car_transform.rotation,
                Vec3::new(0.0, 0.0, -1.0),
            );
            let mut forward = Vec3::new(forward3.x, 0.0, forward3.z);
            let norm = forward.norm();
            if norm > 1e-4 {
                forward /= norm;
            } else {
                forward = Vec3::new(0.0, 0.0, -1.0);
            }

            for (cam_idx, follow) in followers.iter() {
                let Some(mut cam_transform) = transforms.get_mut(cam_idx) else {
                    continue;
                };
                let desired =
                    car_pos - forward * follow.distance + Vec3::new(0.0, follow.height, 0.0);
                // Integrate the smoothing in fixed sub-steps rather than one
                // step of the whole frame delta. `1 - exp(-k*dt)` is only
                // frame-rate independent for a *stationary* target; chasing a
                // moving one it settles at a lag of `v*dt / (1 - exp(-k*dt))`,
                // which grows with `dt`. At a variable frame rate that made the
                // camera's trailing distance breathe frame to frame. Pinning
                // the integration step pins the lag.
                let mut eye = cam_transform.translation;
                let mut remaining = time.delta() as f32;
                while remaining > 0.0 {
                    let step = remaining.min(CAMERA_SMOOTHING_STEP);
                    let blend = 1.0 - (-follow.stiffness * step).exp();
                    eye += (desired - eye) * blend;
                    remaining -= step;
                }

                let target = car_pos + Vec3::new(0.0, 0.8, 0.0);
                let view = nalgebra::Isometry3::look_at_rh(
                    &nalgebra::Point3::from(eye),
                    &nalgebra::Point3::from(target),
                    &Vec3::new(0.0, 1.0, 0.0),
                );
                cam_transform.translation = eye;
                cam_transform.rotation = view.inverse().rotation.into_inner();
            }
        });
        Ok(())
    }
}

/// Menu + HUD + scene flow (#106). Drawn through the [`GameUi`] resource;
/// a host that provides no in-game UI surface (no `GameUi`) makes this a
/// no-op.
///
/// States by [`SceneManager::current`]: the level scene → gameplay HUD, Esc
/// returns to the menu; anything else → main menu with Play (switches to the
/// level) and Quit.
#[derive(Default)]
pub struct GameFlowUi {
    /// Sliding window of raw CPU frame deltas (seconds) behind the HUD's
    /// min/max — long enough to catch the present-queue refill bursts that
    /// follow a hitch (see redlilium-app's `pacing`).
    raw_deltas: VecDeque<f64>,
}

/// Frames of raw-delta history behind the HUD min/max — ~2 s at 60 fps.
const RAW_DELTA_WINDOW: usize = 120;

/// The game camera entity, stashed at spawn so the in-game debug HUD can toggle
/// per-camera post effects (bloom, #151) on it without a query→entity lookup.
struct GameCamera(Entity);

impl ExclusiveSystem for GameFlowUi {
    type Result = ();
    fn run(&mut self, world: &mut World) -> Result<(), SystemError> {
        if !world.has_resource::<GameUi>() {
            return Ok(());
        }
        use redlilium_graphics::egui::egui;
        let egui_ctx = world.resource::<GameUi>().ctx().clone();

        let in_game = {
            let manager = world.resource::<SceneManager>();
            manager.current() == Some(LEVEL_SCENE) && !manager.transitioning()
        };

        if in_game {
            let delta = world.resource::<Time>().delta();
            // The unpaced CPU delta the host published, if it does (the
            // runtime, #149) — paced vs raw side by side is what tells a real
            // missed-vsync cadence from a pacing artifact.
            let raw = world
                .has_resource::<RawFrameDelta>()
                .then(|| world.resource::<RawFrameDelta>().0);
            let raw_stats = raw.map(|raw| {
                if self.raw_deltas.len() == RAW_DELTA_WINDOW {
                    self.raw_deltas.pop_front();
                }
                self.raw_deltas.push_back(raw);
                let (mut min, mut max) = (raw, raw);
                for &d in &self.raw_deltas {
                    min = min.min(d);
                    max = max.max(d);
                }
                (raw, min, max)
            });
            // PhysicsWorld3D appears once SyncPhysicsBodies3D first runs;
            // there is no ordering edge to it, so tolerate the first frame.
            let speed = if world.has_resource::<PhysicsWorld3D>() {
                let physics = world.resource::<PhysicsWorld3D>();
                physics
                    .bodies
                    .iter()
                    .find(|(_, b)| b.is_dynamic())
                    .map(|(_, b)| b.linvel().length())
                    .unwrap_or(0.0)
            } else {
                0.0
            };
            // Post-FX toggles: the checkbox states are derived from whether the
            // game camera carries the component; a change inserts/removes it
            // after the panel (so the passes truly stop when off). Bloom (#151),
            // auto-exposure (#153).
            let camera = world
                .has_resource::<GameCamera>()
                .then(|| world.resource::<GameCamera>().0);
            let mut bloom_on = camera.map(|c| world.get::<CameraBloom>(c).is_some());
            let mut auto_exposure_on = camera.map(|c| world.get::<CameraAutoExposure>(c).is_some());
            egui::Window::new("Car Game — dev")
                .default_pos([10.0, 10.0])
                .resizable(false)
                .show(&egui_ctx, |ui| {
                    ui.label(format!("frame: {:.2} ms", delta * 1000.0));
                    if let Some((raw, min, max)) = raw_stats {
                        ui.label(format!(
                            "raw: {:.2} ms  [{:.1}..{:.1}]",
                            raw * 1000.0,
                            min * 1000.0,
                            max * 1000.0
                        ));
                    }
                    ui.label(format!("speed: {speed:.1} m/s"));
                    if let Some(on) = bloom_on.as_mut() {
                        ui.checkbox(on, "Bloom");
                    }
                    if let Some(on) = auto_exposure_on.as_mut() {
                        ui.checkbox(on, "Auto-exposure");
                    }
                    ui.label("WASD — drive, Esc — menu");
                });
            if let (Some(camera), Some(on)) = (camera, bloom_on) {
                let has = world.get::<CameraBloom>(camera).is_some();
                if on && !has {
                    let _ = world.insert(camera, CameraBloom::default());
                } else if !on && has {
                    let _ = world.remove::<CameraBloom>(camera);
                }
            }
            if let (Some(camera), Some(on)) = (camera, auto_exposure_on) {
                let has = world.get::<CameraAutoExposure>(camera).is_some();
                if on && !has {
                    let _ = world.insert(camera, CameraAutoExposure::default());
                } else if !on && has {
                    let _ = world.remove::<CameraAutoExposure>(camera);
                }
            }
            if world
                .resource::<WindowInput>()
                .is_key_pressed(KeyCode::Escape)
            {
                world.resource_mut::<SceneManager>().switch_to(MENU_SCENE);
            }
        } else {
            let transitioning = world.resource::<SceneManager>().transitioning();
            egui::Window::new("Car Game")
                .collapsible(false)
                .resizable(false)
                .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
                .show(&egui_ctx, |ui| {
                    ui.set_min_width(180.0);
                    ui.vertical_centered(|ui| {
                        ui.heading("Car Game");
                        ui.add_space(12.0);
                        if transitioning {
                            ui.label("Loading…");
                            return;
                        }
                        if ui.button("Play").clicked() {
                            world.resource_mut::<SceneManager>().switch_to(LEVEL_SCENE);
                        }
                        // A browser tab has no process to exit (#100).
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            ui.add_space(4.0);
                            if ui.button("Quit").clicked() {
                                world.resource_mut::<AppControl>().request_exit();
                            }
                        }
                    });
                });
        }
        Ok(())
    }
}

/// The car game plugin: `register_types` declares the game's components (for
/// every hosting world, including the editor's), `build` adds systems (game
/// worlds only), `spawn_scene` spawns the persistent camera and enters the
/// menu (skipped on reload — the scene comes from a snapshot).
pub struct CarGamePlugin;

impl Plugin for CarGamePlugin {
    fn register_types(&self, world: &mut World) {
        // Level-graph components (roads/terrain authoring) come from the
        // levels crate; forwarding here is what makes every hosting world —
        // editor included — understand them.
        redlilium_levels::LevelsPlugin.register_types(world);
        world.register_inspector::<CarController>();
        world.register_inspector::<FollowCamera>();
        world.register_inspector::<CarSpawn>();
    }

    fn build_editing_view(&self, view: &mut redlilium_runtime::EditingView<'_>) {
        redlilium_levels::LevelsPlugin.build_editing_view(view);
    }

    fn build(&self, app: &mut App) {
        log::info!("CarGamePlugin::build");
        // Exclusive: the HUD's bloom toggle (#151) inserts/removes a component,
        // which needs &mut World.
        app.schedule_mut::<Update>()
            .add_exclusive(GameFlowUi::default());

        // Marker-driven car spawn (#105), right after scene swaps land so the
        // car exists the same frame the level appears. `build` runs only in a
        // game world (App::new's composition), so ApplySceneTransitions is
        // always there to order against.
        let pre = app.schedule_mut::<redlilium_ecs::PreUpdate>();
        pre.add_exclusive(SpawnCarAtMarkers);
        pre.add_edge::<redlilium_ecs::ApplySceneTransitions, SpawnCarAtMarkers>()
            .expect("no cycle");

        // Physics pipeline runs at a FIXED timestep (the FixedUpdate
        // accumulator), so simulation speed is decoupled from frame rate: one
        // 1/60 step per accumulated 1/60 of real time — 0 steps on a fast
        // frame, N to catch up a slow one — instead of exactly one step per
        // rendered frame. The old per-frame stepping ran the world in
        // frame-rate-dependent slow-motion and juddered under full-screen load
        // (equal sim steps shown at unequal real intervals). The drive system
        // sits between body sync and the step; StepPhysics3D reads the fixed
        // timestep from `Time::fixed_delta`.
        // Physics ticks deliberately below the render rate; render-side
        // interpolation (below) hides the mismatch, so this is a pure
        // simulation-fidelity vs CPU dial, not a smoothness one.
        app.schedules_mut().set_fixed_timestep(1.0 / 45.0);

        let fixed = app.schedule_mut::<redlilium_ecs::FixedUpdate>();
        fixed.add_exclusive(SyncPhysicsBodies3D);
        fixed.add(DriveCar);
        fixed.add(StepPhysics3D);
        fixed.add(RecordPhysicsPose);
        fixed
            .add_edge::<SyncPhysicsBodies3D, DriveCar>()
            .expect("no cycle");
        fixed
            .add_edge::<DriveCar, StepPhysics3D>()
            .expect("no cycle");
        // Snapshot the pose the step just wrote, once per fixed step.
        fixed
            .add_edge::<StepPhysics3D, RecordPhysicsPose>()
            .expect("no cycle");

        // Interpolate the two most recent fixed steps into Transform, then let
        // the camera follow that (so it tracks the on-screen car, not the raw
        // step), then propagate — the interpolated pose is what renders and
        // what the motion-vector history snapshots.
        let post = app.schedule_mut::<PostUpdate>();
        post.add(InterpolatePhysics);
        post.add(UpdateFollowCamera);
        post.add_edge::<InterpolatePhysics, UpdateFollowCamera>()
            .expect("no cycle");
        post.add_edge::<UpdateFollowCamera, UpdateGlobalTransforms>()
            .expect("no cycle");
    }

    fn spawn_scene(&self, app: &mut App) {
        let aspect = app.initial_aspect();
        let world = app.world_mut();

        // Persistent third-person camera — game-owned, survives scene swaps.
        let follow = FollowCamera::default();
        let eye = Vec3::new(0.0, follow.height, follow.distance);
        let view = nalgebra::Isometry3::look_at_rh(
            &nalgebra::Point3::from(eye),
            &nalgebra::Point3::from(Vec3::new(0.0, 0.8, 0.0)),
            &Vec3::new(0.0, 1.0, 0.0),
        );
        let cam_transform = Transform::new(
            eye,
            view.inverse().rotation.into_inner(),
            Vec3::new(1.0, 1.0, 1.0),
        );
        let camera = world.spawn();
        world
            .insert(camera, Camera::perspective(FRAC_PI_4, aspect, 0.1, 500.0))
            .unwrap();
        // The game renders through the standard deferred PBR/IBL path (#144)
        // with TAA (#148: jitter + accumulation ride the same opt-in).
        world
            .insert(
                camera,
                redlilium_ecs::RenderPath::named(redlilium_ecs::DEFERRED_PIPELINE),
            )
            .unwrap();
        world
            .insert(camera, redlilium_ecs::TemporalJitter::default())
            .unwrap();
        // Tile-based motion blur (#149): the follow camera pans with the car,
        // so the environment streaks — motion blur sells the speed. A shorter
        // shutter than the 0.5 default keeps it light rather than smeary.
        world
            .insert(
                camera,
                redlilium_ecs::MotionBlur {
                    shutter: 0.35,
                    samples: 15,
                },
            )
            .unwrap();
        // IBL environment as a per-camera asset (#145): the std sunrise set.
        world
            .insert(camera, redlilium_ecs::CameraEnvironment::default())
            .unwrap();
        // Screen-space ambient occlusion (#150) grounds the IBL ambient; its
        // per-frame kernel rotation rides the TAA above.
        world
            .insert(camera, redlilium_ecs::CameraAmbientOcclusion::default())
            .unwrap();
        // HDR bloom (#151) — a subtle default glow on highlights.
        world
            .insert(camera, redlilium_ecs::CameraBloom::default())
            .unwrap();
        // Auto-exposure (#153) — the compute metering adapts the exposure to
        // the scene (drives it in place of a manual CameraExposure); the dev
        // HUD can toggle it off to compare.
        world
            .insert(camera, redlilium_ecs::CameraAutoExposure::default())
            .unwrap();
        world.insert(camera, cam_transform).unwrap();
        world
            .insert(camera, GlobalTransform(cam_transform.to_matrix()))
            .unwrap();
        world.insert(camera, Visibility::VISIBLE).unwrap();
        world.insert(camera, follow).unwrap();
        // Remember the camera so the in-game HUD's bloom toggle (#151) can find
        // it without a query.
        world.insert_resource(GameCamera(camera));

        // World content comes from scene assets, starting at the menu (#106).
        // A host that wants a different start scene overrides it through
        // App::boot's start_scene parameter (e.g. CAR_GAME_SCENE in main.rs),
        // not in here.
        world.resource_mut::<SceneManager>().switch_to(MENU_SCENE);
    }
}

/// The level as authored into the [`LEVEL_SCENE`] asset (#105): geometry plus
/// the [`CarSpawn`] marker. The car itself is *not* part of the scene — it is
/// spawned at load time by [`SpawnCarAtMarkers`], so an editor-authored level
/// only needs cubes, colliders, and one marker.
pub fn spawn_level_scene(world: &mut World) {
    spawn_sun(world);
    spawn_level_geometry(world);
    let marker = world.spawn();
    world
        .insert(
            marker,
            Transform::from_translation(Vec3::new(0.0, 0.5, 0.0)),
        )
        .unwrap();
    world.insert(marker, CarSpawn).unwrap();
}

/// The scenes' key light (#146: lights are ECS components; the deferred path
/// no longer has a built-in sun). Direction and energy match the retired
/// constant, so the lit look carries over.
pub fn spawn_sun(world: &mut World) {
    let sun = world.spawn();
    let transform = Transform::new(
        Vec3::new(0.0, 10.0, 0.0),
        redlilium_core::math::quat_looking_along(Vec3::new(-0.75, -0.40, -0.75)),
        Vec3::new(1.0, 1.0, 1.0),
    );
    world.insert(sun, Name::new("Sun")).unwrap();
    world.insert(sun, transform).unwrap();
    world
        .insert(sun, GlobalTransform(transform.to_matrix()))
        .unwrap();
    world.insert(sun, Visibility::VISIBLE).unwrap();
    world
        .insert(sun, DirectionalLight::new(Vec3::new(1.0, 0.98, 0.95), 1.6))
        .unwrap();
}

/// Spawn the drivable chassis at `position`: dynamic box, 1×0.6×2 m.
/// Near-frictionless collider: grip is modeled by `DriveCar`'s lateral
/// velocity bleed (see [`LATERAL_GRIP`]).
pub fn spawn_car(world: &mut World, position: Vec3) -> redlilium_ecs::Entity {
    // Glossy red pbr paint (game-mount asset, parented on the std pbr
    // material) — the standard deferred path draws pbr-model materials.
    let material = MaterialInstanceSource {
        guid: Guid::stable("materials/car.matinst"),
    };
    let car_transform = Transform::new(position, Quat::identity(), Vec3::new(1.0, 0.6, 2.0));
    let car = spawn_box(world, material, car_transform);
    world
        .insert(
            car,
            RigidBody3D::dynamic()
                .with_linear_damping(0.6)
                .with_angular_damping(3.0),
        )
        .unwrap();
    world
        .insert(
            car,
            Collider3D::cuboid(0.5, 0.3, 1.0)
                .with_friction(0.05)
                .with_density(80.0),
        )
        .unwrap();
    world.insert(car, CarController::default()).unwrap();
    car
}

/// Exclusive `PreUpdate` system, ordered after `ApplySceneTransitions`: when
/// the world has a [`CarSpawn`] marker but no car, spawn the chassis at the
/// marker. The car is tagged as a [`SceneMember`] of the current scene, so a
/// scene switch despawns it together with the level that spawned it.
pub struct SpawnCarAtMarkers;

impl redlilium_ecs::ExclusiveSystem for SpawnCarAtMarkers {
    type Result = ();

    fn run(&mut self, world: &mut World) -> Result<(), SystemError> {
        // Only materialize the car once a scene is instantiated: before that
        // (menu, mid-transition, bare test worlds) a marker is inert data.
        let owning_scene = world
            .has_resource::<SceneManager>()
            .then(|| {
                world
                    .resource::<SceneManager>()
                    .current()
                    .map(str::to_string)
            })
            .flatten();
        let Some(owning_scene) = owning_scene else {
            return Ok(());
        };
        let has_car = world
            .read_all::<CarController>()
            .map(|cars| cars.iter().next().is_some())
            .unwrap_or(false);
        if has_car {
            return Ok(());
        }
        let marker_pos = {
            let Ok(markers) = world.read_all::<CarSpawn>() else {
                return Ok(());
            };
            let Ok(transforms) = world.read_all::<Transform>() else {
                return Ok(());
            };
            markers
                .iter()
                .next()
                .and_then(|(idx, _)| transforms.get(idx).map(|t| t.translation))
        };
        let Some(position) = marker_pos else {
            return Ok(());
        };
        let car = spawn_car(world, position);
        let _ = world.insert(
            car,
            redlilium_ecs::SceneMember {
                scene: owning_scene,
            },
        );
        log::info!("car spawned at marker ({position:?})");
        Ok(())
    }
}

/// Spawn the level geometry: frictionless ground slab and the obstacle ring.
/// Used by the scene generator ([`spawn_level_scene`]).
pub fn spawn_level_geometry(world: &mut World) {
    let material = MaterialInstanceSource {
        guid: Guid::stable("materials/pbr.matinst"),
    };

    // Ground slab: static body, 40×0.2×40 m. Frictionless: rapier averages
    // the pair's coefficients, so any ground friction shows up as yaw
    // resistance on the flat-resting chassis (at µ_avg ≈ 0.5 the steering
    // torque physically cannot spin the car). Grip is DriveCar's lateral
    // bleed, not contact friction.
    let ground_transform = Transform::new(
        Vec3::new(0.0, -0.1, 0.0),
        Quat::identity(),
        Vec3::new(40.0, 0.2, 40.0),
    );
    let ground = spawn_box(world, material.clone(), ground_transform);
    world.insert(ground, RigidBody3D::fixed()).unwrap();
    world
        .insert(
            ground,
            Collider3D::cuboid(20.0, 0.1, 20.0).with_friction(0.0),
        )
        .unwrap();

    // Obstacle ring: static 1 m cubes to drive around and into.
    for i in 0..8 {
        let angle = i as f32 / 8.0 * std::f32::consts::TAU;
        let obstacle_transform =
            Transform::from_translation(Vec3::new(angle.cos() * 10.0, 0.5, angle.sin() * 10.0));
        let obstacle = spawn_box(world, material.clone(), obstacle_transform);
        world.insert(obstacle, RigidBody3D::fixed()).unwrap();
        world
            .insert(obstacle, Collider3D::cuboid(0.5, 0.5, 0.5))
            .unwrap();
    }
}

/// Spawn the menu backdrop: a decorative ring of cubes for the camera to look
/// at while the menu is up. Authored into [`MENU_SCENE`] by `gen_scenes`.
pub fn spawn_menu_backdrop(world: &mut World) {
    spawn_sun(world);
    let material = MaterialInstanceSource {
        guid: Guid::stable("materials/pbr.matinst"),
    };
    for i in 0..12 {
        let angle = i as f32 / 12.0 * std::f32::consts::TAU;
        let transform = Transform::new(
            Vec3::new(
                angle.cos() * 6.0,
                (i % 3) as f32 * 0.8,
                angle.sin() * 6.0 - 8.0,
            ),
            Quat::identity(),
            Vec3::new(0.8, 0.8, 0.8),
        );
        spawn_box(world, material.clone(), transform);
    }
}

/// Road-graph playground (docs/DESIGN_PROCEDURAL_LEVELS.md, prototype): a
/// short S-curve of [`RoadNode`](redlilium_levels::RoadNode) cross-sections
/// joined by [`RoadSegment`](redlilium_levels::RoadSegment)s, plus one lone
/// node. No geometry — the levels editing-view overlay draws the graph; move
/// and rotate nodes with the gizmo and the patches follow.
pub fn spawn_levels_playground(world: &mut World) {
    use redlilium_levels::{RoadNode, RoadSegment};

    spawn_sun(world);

    let node = |world: &mut World, x: f32, z: f32, yaw: f32| {
        let entity = world.spawn();
        let transform = Transform::new(
            Vec3::new(x, 0.0, z),
            redlilium_core::math::quat_from_rotation_y(yaw),
            Vec3::new(1.0, 1.0, 1.0),
        );
        world.insert(entity, transform).unwrap();
        world
            .insert(entity, GlobalTransform(transform.to_matrix()))
            .unwrap();
        world.insert(entity, RoadNode::default()).unwrap();
        entity
    };

    let n1 = node(world, 0.0, 0.0, 0.0);
    let n2 = node(world, 2.5, 11.0, 0.4);
    let n3 = node(world, 9.2, 19.8, 0.9);
    let n4 = node(world, 19.2, 24.3, 1.4);
    // A lone cross-section: what a node looks like before it is connected.
    node(world, -8.0, 6.0, -0.5);

    let road = |world: &mut World, a, b| {
        let road = world.spawn();
        world
            .insert(
                road,
                RoadSegment {
                    a,
                    b,
                    ..RoadSegment::default()
                },
            )
            .unwrap();
        road
    };
    let r1 = road(world, n1, n2);
    road(world, n2, n3);
    road(world, n3, n4);

    // A driveway: a node glued to part of the first road's right edge (its
    // transform is derived from the parent edge — see
    // `redlilium_levels::EdgeAnchor`) plus an ordinary road from it to an
    // outer exit node. Socket convention: the exit's +Z faces the road; the
    // future building fills the −Z side behind it.
    let glued = node(world, 0.0, 0.0, 0.0);
    world
        .insert(
            glued,
            redlilium_levels::EdgeAnchor {
                parent_road: r1,
                right_edge: true,
                u_min: 0.35,
                u_max: 0.65,
            },
        )
        .unwrap();
    let exit = node(world, 9.0, 5.5, -std::f32::consts::FRAC_PI_2);
    let driveway = world.spawn();
    world
        .insert(
            driveway,
            RoadSegment {
                a: glued,
                b: exit,
                b_from_front: true,
                ..RoadSegment::default()
            },
        )
        .unwrap();

    // Junction examples (docs/DESIGN_PROCEDURAL_LEVELS.md): connectors are
    // ordinary nodes with +Z outward; the loop re-derives on every edit.
    use redlilium_levels::Junction;
    use redlilium_levels::junction::stamp_connector_transform;
    let connector = |world: &mut World, transform: Transform| {
        let e = world.spawn();
        world.insert(e, transform).unwrap();
        world
            .insert(e, GlobalTransform(transform.to_matrix()))
            .unwrap();
        world
            .insert(e, redlilium_levels::RoadNode::default())
            .unwrap();
        e
    };

    // A 4-way cross with two exit roads.
    let cross_center = Vec3::new(34.0, 0.0, 10.0);
    let cross: Vec<_> = (0..4)
        .map(|i| {
            let yaw = i as f32 * std::f32::consts::FRAC_PI_2;
            connector(world, stamp_connector_transform(cross_center, yaw, 8.0))
        })
        .collect();
    let j = world.spawn();
    world
        .insert(
            j,
            Junction {
                connectors: cross.clone(),
                ..Junction::default()
            },
        )
        .unwrap();
    let exit_north = node(world, 34.0, 30.0, 0.0);
    let exit_east = node(world, 54.0, 10.0, std::f32::consts::FRAC_PI_2);
    road(world, cross[0], exit_north);
    road(world, cross[1], exit_east);

    // A 3-way (Y) junction: the same model at N = 3, no exits.
    let y_center = Vec3::new(-16.0, 0.0, 22.0);
    let y: Vec<_> = [0.0f32, 2.094, -2.094]
        .into_iter()
        .map(|yaw| connector(world, stamp_connector_transform(y_center, yaw, 6.0)))
        .collect();
    let j = world.spawn();
    world
        .insert(
            j,
            Junction {
                connectors: y,
                ..Junction::default()
            },
        )
        .unwrap();

    // Bake the edge-anchored nodes' derived transforms so the scene ships
    // settled — the editor's derive system then has nothing to rewrite.
    redlilium_levels::settle_edge_anchors(world);
}

fn spawn_box(
    world: &mut World,
    material: MaterialInstanceSource,
    transform: Transform,
) -> redlilium_ecs::Entity {
    let entity = world.spawn();
    world.insert(entity, transform).unwrap();
    world
        .insert(entity, GlobalTransform(transform.to_matrix()))
        .unwrap();
    world.insert(entity, Visibility::VISIBLE).unwrap();
    world
        .insert(
            entity,
            MeshRenderer::single(Primitive::new(
                MeshSource::Generated(MeshGenerator::cube(0.5)),
                material,
            )),
        )
        .unwrap();
    entity
}

// Export the ADR-020 game symbols so this cdylib is loadable by the editor's
// GameHost (#45). Same caveat as `redlilium-demos`: the macro expands
// `#[no_mangle]` symbols into a crate built as BOTH cdylib and rlib — sound
// while only this package's own bin links the rlib, but a host binary linking
// two such rlibs would fail with duplicate symbols.
redlilium_runtime::redlilium_game_module!(CarGamePlugin);

/// The `game/assets` pack compiled into the wasm binary (#108) — a browser
/// has no local disk, so the mount is served from memory. The table is
/// generated by `build.rs` from the pack directory.
#[cfg(target_arch = "wasm32")]
mod embedded_pack {
    include!(concat!(env!("OUT_DIR"), "/embedded_pack.rs"));
}

/// Browser entry point: boot the runtime with the same config as the native
/// binary, plus the embedded pack for the `game` mount (`std-assets` is
/// embedded by the runtime itself). `wasm-bindgen(start)` invokes this when
/// the wasm module initialises; the app crate installs the console logger and
/// panic hook.
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen::prelude::wasm_bindgen(start)]
pub fn start() {
    redlilium_runtime::run(
        redlilium_runtime::GameConfig {
            title: "Car Game".to_string(),
            mounts: vec![("std", "std-assets"), ("game", "game/assets")],
            embedded_packs: vec![("game/assets", embedded_pack::GAME_ASSETS)],
            ..Default::default()
        },
        CarGamePlugin,
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use redlilium_ecs::{EcsRunner, Entity, Schedules};

    /// Minimal single-future executor for the scene pipeline's pure-async
    /// stages (memory VFS + RON parse) — no reactor needed.
    fn block_on<F: std::future::Future + ?Sized>(mut fut: std::pin::Pin<Box<F>>) -> F::Output {
        use std::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};
        fn noop_raw() -> RawWaker {
            const VTABLE: RawWakerVTable =
                RawWakerVTable::new(|_| noop_raw(), |_| {}, |_| {}, |_| {});
            RawWaker::new(std::ptr::null(), &VTABLE)
        }
        let waker = unsafe { Waker::from_raw(noop_raw()) };
        let mut cx = Context::from_waker(&waker);
        loop {
            match fut.as_mut().poll(&mut cx) {
                Poll::Ready(v) => return v,
                Poll::Pending => std::thread::yield_now(),
            }
        }
    }

    /// The #106 flow against the committed scene assets: menu → level → menu.
    /// Reads the real generated `.scene` files, so a stale `gen_scenes` output
    /// (or a format break) fails here.
    #[test]
    fn menu_level_flow_uses_generated_scene_assets() {
        use redlilium_assets::{AssetDb, AssetProcessor};
        use redlilium_ecs::{ApplySceneTransitions, SceneLoader, SceneManager, SceneMember};
        use redlilium_vfs::{MemoryProvider, Vfs};

        let assets_root = concat!(env!("CARGO_MANIFEST_DIR"), "/assets");

        // Serve the committed files from memory (no reactor in tests).
        let provider = MemoryProvider::new();
        for path in [MENU_SCENE, LEVEL_SCENE] {
            let bytes = std::fs::read(format!("{assets_root}/{path}"))
                .expect("scene file exists — run `cargo run -p car-game --bin gen_scenes`");
            provider.insert(path, bytes);
        }
        let mut vfs = Vfs::new();
        vfs.mount("game", provider);

        let mut db = AssetDb::new();
        let db_text =
            std::fs::read_to_string(format!("{assets_root}/assets.db")).expect("assets.db exists");
        let conflicts = db.merge_ron("game", &db_text).expect("assets.db parses");
        assert!(conflicts.is_empty());

        let instance = redlilium_graphics::GraphicsInstance::new().expect("graphics instance");
        let device = instance.create_device().expect("device");
        let processor = AssetProcessor::builder(vfs, device)
            .with_loader::<SceneLoader>()
            .build();

        let mut world = World::new();
        redlilium_ecs::register_std_components(&mut world);
        redlilium_ecs::register_rendering_components(&mut world);
        world.register_inspector::<CarController>();
        world.register_inspector::<FollowCamera>();
        world.register_inspector::<CarSpawn>();
        world.register_inspector::<SceneMember>();
        world.insert_resource(db);
        world.insert_resource(processor);
        world.insert_resource(SceneManager::default());

        let mut apply = ApplySceneTransitions;
        let mut spawn_cars = SpawnCarAtMarkers;
        let mut switch_and_settle = |world: &mut World, path: &str| {
            world.resource_mut::<SceneManager>().switch_to(path);
            for _ in 0..8 {
                redlilium_ecs::system::run_exclusive_system_once(&mut apply, world).unwrap();
                // The plugin orders the marker spawn right after transitions.
                redlilium_ecs::system::run_exclusive_system_once(&mut spawn_cars, world).unwrap();
                let mut processor = world.resource_mut::<AssetProcessor>();
                for _ in 0..16 {
                    let tasks = processor.drain_tasks();
                    for (_executor, fut) in tasks {
                        block_on(fut);
                    }
                    processor.collect();
                }
            }
        };
        let cars = |world: &World| {
            world
                .read_all::<CarController>()
                .map(|c| c.iter().count())
                .unwrap_or(0)
        };

        switch_and_settle(&mut world, MENU_SCENE);
        assert_eq!(cars(&world), 0, "menu backdrop has no car");
        assert!(
            world.read_all::<MeshRenderer>().unwrap().iter().count() >= 12,
            "menu backdrop cubes present"
        );

        switch_and_settle(&mut world, LEVEL_SCENE);
        assert_eq!(
            cars(&world),
            1,
            "car spawned at the scene's CarSpawn marker (#105)"
        );
        assert_eq!(
            world.read_all::<CarSpawn>().unwrap().iter().count(),
            1,
            "level scene carries exactly one spawn marker"
        );

        // Physics authoring data must survive the scene roundtrip (the
        // descriptors used to be #[skip_serialization] — an undrivable level).
        assert_eq!(
            world.read_all::<RigidBody3D>().unwrap().iter().count(),
            10,
            "ground + 8 obstacles + car carry rigid bodies"
        );

        // Transform propagation must pick up scene-instantiated entities:
        // after one propagation pass the ground's world matrix reflects its
        // authored scale, not the identity the required-component default
        // inserted (a level of identity matrices renders as an "empty" pile
        // of unit cubes at the origin).
        {
            let mut schedules = Schedules::new();
            schedules
                .get_mut::<PostUpdate>()
                .add(UpdateGlobalTransforms);
            schedules.run_frame(&mut world, &EcsRunner::single_thread(), 1.0 / 60.0);
        }
        let ground_scaled = {
            let transforms = world.read_all::<Transform>().unwrap();
            let globals = world.read_all::<GlobalTransform>().unwrap();
            transforms.iter().any(|(idx, t)| {
                t.scale.x == 40.0
                    && globals
                        .get(idx)
                        .is_some_and(|g| (g.0[(0, 0)] - 40.0).abs() < 1e-3)
            })
        };
        assert!(
            ground_scaled,
            "ground GlobalTransform must reflect the authored 40x scale after propagation"
        );

        switch_and_settle(&mut world, MENU_SCENE);
        assert_eq!(cars(&world), 0, "car despawns with its scene");
    }

    /// Headless world with ground + chassis, wired exactly like the plugin's
    /// Update schedule (body sync → drive → step).
    fn drive_rig() -> (World, Schedules, EcsRunner, Entity) {
        let mut world = World::new();
        redlilium_ecs::register_std_components(&mut world);
        world.register_inspector::<CarController>();

        // Ground slab.
        let ground = world.spawn();
        world
            .insert(
                ground,
                Transform::from_translation(Vec3::new(0.0, -0.1, 0.0)),
            )
            .unwrap();
        world.insert(ground, RigidBody3D::fixed()).unwrap();
        world
            .insert(
                ground,
                Collider3D::cuboid(20.0, 0.1, 20.0).with_friction(0.0),
            )
            .unwrap();

        // Car chassis, as spawn_scene builds it.
        let car = world.spawn();
        world
            .insert(car, Transform::from_translation(Vec3::new(0.0, 0.5, 0.0)))
            .unwrap();
        world
            .insert(
                car,
                RigidBody3D::dynamic()
                    .with_linear_damping(0.6)
                    .with_angular_damping(3.0),
            )
            .unwrap();
        world
            .insert(
                car,
                Collider3D::cuboid(0.5, 0.3, 1.0)
                    .with_friction(0.05)
                    .with_density(80.0),
            )
            .unwrap();
        world.insert(car, CarController::default()).unwrap();

        world.insert_resource(WindowInput::default());

        let mut schedules = Schedules::new();
        {
            // Mirror the production wiring: physics in FixedUpdate. The tests
            // drive one 1/60 `run_frame` per loop, so the accumulator runs
            // exactly one fixed step per call — same trajectory as before.
            let fixed = schedules.get_mut::<redlilium_ecs::FixedUpdate>();
            fixed.add_exclusive(SyncPhysicsBodies3D);
            fixed.add(DriveCar);
            fixed.add(StepPhysics3D);
            fixed
                .add_edge::<SyncPhysicsBodies3D, DriveCar>()
                .expect("no cycle");
            fixed
                .add_edge::<DriveCar, StepPhysics3D>()
                .expect("no cycle");
        }

        (world, schedules, EcsRunner::single_thread(), car)
    }

    fn hold_keys(world: &mut World, keys: &[KeyCode]) {
        let mut input = WindowInput::default();
        for key in keys {
            input.on_key_pressed(*key);
        }
        world.insert_resource(input);
    }

    /// The arcade loop end-to-end, headless: holding W must move the car
    /// along its forward (-Z) while the ground keeps it from falling through.
    #[test]
    fn car_drives_forward_and_rests_on_ground() {
        let (mut world, mut schedules, runner, car) = drive_rig();
        hold_keys(&mut world, &[KeyCode::W]);

        for _ in 0..180 {
            schedules.run_frame(&mut world, &runner, 1.0 / 60.0);
        }

        let t = *world.get::<Transform>(car).unwrap();
        assert!(
            t.translation.z < -2.0,
            "car must drive forward (-Z) under W, got z = {}",
            t.translation.z
        );
        assert!(
            t.translation.y > 0.0 && t.translation.y < 1.0,
            "car must rest on the ground, got y = {}",
            t.translation.y
        );
    }

    /// Holding W+A must yaw the car and bend its path: after a few seconds
    /// the heading departs from straight -Z and the car has drifted off the
    /// Z axis in X.
    #[test]
    fn car_turns_under_steering() {
        let (mut world, mut schedules, runner, car) = drive_rig();
        hold_keys(&mut world, &[KeyCode::W, KeyCode::A]);

        for _ in 0..240 {
            schedules.run_frame(&mut world, &runner, 1.0 / 60.0);
        }

        let t = *world.get::<Transform>(car).unwrap();
        let forward = redlilium_core::math::quat_rotate_vec3(t.rotation, Vec3::new(0.0, 0.0, -1.0));
        assert!(
            forward.x.abs() > 0.3,
            "heading must yaw away from -Z under steering, forward = ({:.2}, {:.2}, {:.2})",
            forward.x,
            forward.y,
            forward.z
        );
        assert!(
            t.translation.x.abs() > 1.0,
            "path must bend off the Z axis, got x = {}",
            t.translation.x
        );
    }
}
