#![allow(refining_impl_trait)]
//! # RedLilium ECS
//!
//! Custom Entity-Component-System with integrated async compute support.
//!
//! ## Core Types
//!
//! - [`Entity`] — Lightweight generational entity identifier
//! - [`World`] — Central ECS container owning entities, components, and resources
//! - [`Ref`] / [`RefMut`] — Borrow-checked access to component storages
//! - [`ContainsChecker`] — Filter for `With<T>` / `Without<T>` queries
//!
//! ## Systems & Scheduling
//!
//! - [`System`] — Async system trait with compile-time borrow safety
//! - [`SystemContext`] — Context for component access, compute, and commands
//! - [`SystemsContainer`] — System registration with dependency tracking
//! - [`EcsRunner`] — Single-threaded or multi-threaded system executor
//!
//! ## Access Types
//!
//! - [`Read`] / [`Write`] — Component access markers for lock tuples
//! - [`OptionalRead`] / [`OptionalWrite`] — Non-panicking component access
//! - [`Res`] / [`ResMut`] — Resource access markers
//!
//! ## Async Compute
//!
//! - [`ComputePool`] — Spawn and manage async background tasks
//! - [`TaskHandle`] — Retrieve results from completed tasks
//! - [`Priority`] — Task priority levels (Critical, High, Low)
//! - [`yield_now`] — Cooperative yielding for async tasks
//!
//! See `DESIGN.md` in this crate for architecture decisions and goals.

// Self-referencing re-export so that `redlilium_ecs::` paths generated by
// the `ecs-macro` derive proc-macro resolve correctly even when used from
// inside this crate.
#[doc(hidden)]
extern crate self as redlilium_ecs;

mod access_set;
mod bundle;
mod command_collector;
mod commands;
pub mod component;
pub mod components;
mod compute;
mod compute_context;
mod entity;
mod events;
mod function_system;
pub mod hierarchy;
pub mod inspect;
mod io_runtime;
mod lock_request;
mod main_thread_dispatcher;
mod main_thread_resource;
#[cfg(any(
    feature = "physics-3d",
    feature = "physics-3d-f32",
    feature = "physics-2d",
    feature = "physics-2d-f32"
))]
pub mod physics;
mod query;
mod query_guard;
mod resource;
mod runner;
mod sparse_set;
mod spawn;
mod system;
pub mod system_context;
pub mod systems;
mod systems_container;
#[cfg(feature = "inspector")]
pub mod ui;
mod world;

// Core types
pub use commands::CommandBuffer;
pub use component::Component;
pub use compute::{ComputePool, TaskHandle};
pub use ecs_macro::{Bundle, Component};
pub use egui;
pub use entity::Entity;
pub use events::{EventUpdateSystem, Events};
pub use io_runtime::IoRuntime;
pub use query::{AddedFilter, ChangedFilter, ContainsChecker, RemovedFilter, With, Without};
pub use query_guard::QueryGuard;
pub use redlilium_core::compute::{
    ComputeContext, IoHandle, IoRunner, Priority, YieldNow, reset_yield_timer, set_yield_interval,
    yield_now,
};
pub use resource::{Resource, ResourceRef, ResourceRefMut};
pub use sparse_set::{Ref, RefMut, SparseSetInner};
pub use world::{ComponentNotRegistered, World};

pub use compute_context::EcsComputeContext;

// System & scheduling (new API)
pub use access_set::{
    AccessSet, MainThreadRes, MainThreadResMut, OptionalRead, OptionalWrite, Read, Res, ResMut,
    Write,
};
pub use bundle::Bundle;
pub use command_collector::{CommandCollector, SpawnBuilder};
pub use function_system::{FunctionSystem, IntoSystem};
pub use lock_request::LockRequest;
pub use runner::{EcsRunner, EcsRunnerSingleThread, ShutdownError};
pub use system::{System, SystemResult, run_system_blocking};
pub use system_context::SystemContext;
pub use systems_container::{CycleError, Edge, SystemsContainer};

#[cfg(not(target_arch = "wasm32"))]
pub use runner::EcsRunnerMultiThread;

// Standard components & systems (merged from ecs-std)
pub use components::*;
pub use hierarchy::{HierarchyCommands, despawn_recursive, remove_parent, set_parent};
pub use spawn::spawn_scene;
pub use systems::{UpdateCameraMatrices, UpdateGlobalTransforms};

/// Register all standard component types with the world.
///
/// Registers storage, inspector metadata, and (where applicable) default
/// insertion support. Call this before running systems or using the inspector.
pub fn register_std_components(world: &mut World) {
    // Inspector-enabled components (support "Add Component" via Default)
    world.register_inspector_default::<Transform>();
    world.register_inspector_default::<GlobalTransform>();
    world.register_inspector_default::<Visibility>();
    world.register_inspector_default::<Name>();
    world.register_inspector_default::<DirectionalLight>();
    world.register_inspector_default::<PointLight>();
    world.register_inspector_default::<SpotLight>();

    // Inspector-enabled, readonly (no Default — constructed with parameters)
    world.register_inspector::<Camera>();

    // Hierarchy components (storage only — managed by hierarchy functions)
    world.register_component::<Parent>();
    world.register_component::<Children>();

    // Physics descriptor + handle components (feature-gated)
    #[cfg(any(feature = "physics-3d", feature = "physics-3d-f32"))]
    {
        world.register_inspector_default::<physics::components3d::RigidBody3D>();
        world.register_inspector_default::<physics::components3d::Collider3D>();
        world.register_component::<physics::physics3d::RigidBody3DHandle>();
    }
    #[cfg(any(feature = "physics-2d", feature = "physics-2d-f32"))]
    {
        world.register_inspector_default::<physics::components2d::RigidBody2D>();
        world.register_inspector_default::<physics::components2d::Collider2D>();
        world.register_component::<physics::physics2d::RigidBody2DHandle>();
    }
}
