#![recursion_limit = "256"]
//! # RedLilium ECS
//!
//! Custom Entity-Component-System with integrated async compute support.
//!
//! ## Core Types
//!
//! - [`Entity`] — Lightweight generational entity identifier
//! - [`World`] — Central ECS container owning entities, components, and resources
//! - [`Ref`] / [`RefMut`] — Borrow-checked access to component storages
//! - [`ContainsChecker`] — Filter for `With<T>` / `Without<T>` queries
//!
//! ## Systems & Scheduling
//!
//! - [`System`] — System trait with compile-time borrow safety
//! - [`SystemContext`] — Context for component access, compute, and commands
//! - [`SystemsContainer`] — System registration with dependency tracking
//! - [`EcsRunner`] — Single-threaded or multi-threaded system executor
//!
//! ## Access Types
//!
//! - [`Read`] / [`Write`] — Component access markers for lock tuples
//! - [`OptionalRead`] / [`OptionalWrite`] — Non-panicking component access
//! - [`Res`] / [`ResMut`] — Resource access markers
//!
//! ## Async Compute
//!
//! - [`ComputePool`] — Spawn and manage async background tasks
//! - [`TaskHandle`] — Retrieve results from completed tasks
//! - [`Priority`] — Task priority levels (Critical, High, Low)
//! - [`yield_now`] — Cooperative yielding for async tasks
//!
//! See `DESIGN.md` in this crate for architecture decisions and goals.

// Self-referencing re-export so that `redlilium_ecs::` paths generated by
// the `ecs-macro` derive proc-macro resolve correctly even when used from
// inside this crate.
#[doc(hidden)]
extern crate self as redlilium_ecs;

mod bundle;
mod commands;
pub mod component;
pub mod component_field;
mod compute;
mod entity;
mod events;
pub mod inspect;
mod main_thread_dispatcher;
mod main_thread_resource;
pub mod map_entities;
mod observer;
#[cfg(any(
    feature = "physics-3d",
    feature = "physics-3d-f32",
    feature = "physics-2d",
    feature = "physics-2d-f32"
))]
pub use self::std::physics;
pub mod prefab;
mod query;
mod reactive;
#[cfg(feature = "rendering")]
pub use self::std::rendering;
mod resource;
mod runner;
pub mod serialize;
mod sparse_set;
#[allow(clippy::module_inception)]
pub mod std;
mod system;
pub mod ui;
mod world;

// Core types
pub use commands::CommandBuffer;
pub use component::Component;
pub use component_field::ComponentField;
pub use compute::IoRuntime;
pub use compute::{ComputePool, TaskHandle};
pub use ecs_macro::{Bundle, Component};
pub use egui;
pub use entity::Entity;
pub use events::{EventUpdateSystem, Events};
pub use observer::{OnAdd, OnInsert, OnRemove};
pub use prefab::Prefab;
pub use query::{
    AddedFilter, AnyFilter, ChangedFilter, ContainsChecker, Filter, OrFilter, RemovedFilter, With,
    Without,
};
pub use query::{QueryGuard, QueryItem, QueryIter, ResMutRef};
pub use reactive::{HasTriggers, Triggers};
pub use redlilium_core::compute::{
    CancellationToken, Cancelled, Checkpoint, ComputeContext, ComputeMutex, ComputeMutexGuard,
    ComputeMutexLock, ComputeReadGuard, ComputeRwLock, ComputeRwLockRead, ComputeRwLockWrite,
    ComputeWriteGuard, IoHandle, IoRunner, Priority, YieldNow, reset_yield_timer,
    set_yield_interval, yield_now,
};
pub use resource::{Resource, ResourceRef, ResourceRefMut};
pub use sparse_set::{Mut, Ref, RefMut, SparseSetInner};
pub use world::{ComponentNotRegistered, InspectResult, World, WorldError, set_component_actions};

pub use compute::EcsComputeContext;

// System & scheduling (new API)
pub use bundle::Bundle;
pub use commands::{CommandCollector, SpawnBuilder};
pub use query::LockRequest;
pub use query::{
    AccessSet, Added, Any, Changed, MainThreadRes, MainThreadResMut, MaybeAdded, MaybeChanged,
    MaybeRemoved, OptionalRead, OptionalWrite, Or, Read, ReadAll, Removed, Res, ResMut, Write,
    WriteAll,
};
pub use runner::{EcsRunner, EcsRunnerSingleThread, ShutdownError};
pub use system::ParConfig;
pub use system::SystemContext;
pub use system::{
    AccessConflict, AmbiguityInfo, RunDiagnostics, RunReport, RunResult, SystemTiming, TimingReport,
};
pub use system::{ApplyStateTransition, NextState, State, StateTransition, States, init_state};
pub use system::{Condition, ConditionMode, ConditionResult};
pub use system::{CycleError, Edge, SystemSet, SystemsContainer};
pub use system::{
    ExclusiveFunctionSystem, ExclusiveSystem, ReadOnlyExclusiveFunctionSystem,
    ReadOnlyExclusiveSystem, System, SystemError, panic_payload_to_string,
    run_exclusive_system_blocking, run_exclusive_system_once,
    run_read_only_exclusive_system_blocking, run_system_blocking, run_system_once,
};
pub use system::{
    FixedUpdate, PostUpdate, PreUpdate, Render, ScheduleId, ScheduleLabel, Schedules, Startup,
    Time, Update,
};
pub use system::{
    ForEach, ForEachAccess, ForEachSystem, FunctionSystem, IntoSystem, ParForEach,
    ParForEachSystem, for_each, par_for_each,
};

#[cfg(not(target_arch = "wasm32"))]
pub use runner::EcsRunnerMultiThread;

// Standard components & systems
pub use self::std::components;
pub use self::std::components::*;
pub use self::std::hierarchy::{
    HierarchyCommands, despawn_recursive, disable, enable, mark_editor, mark_static, remove_parent,
    set_parent, unmark_editor, unmark_static,
};
pub use self::std::spawn::spawn_scene;
pub use self::std::systems;
#[cfg(feature = "rendering")]
pub use self::std::systems::DrawGrid;
#[cfg(feature = "rendering")]
pub use self::std::systems::{DrawSelectionAabb, SelectionAabbMode};
pub use self::std::systems::{UpdateCameraMatrices, UpdateFreeFlyCamera, UpdateGlobalTransforms};

// Rendering components, resources, and systems (feature-gated)
#[cfg(feature = "rendering")]
pub use redlilium_debug_drawer::{DebugDrawer, DebugDrawerRenderer};
#[cfg(feature = "rendering")]
pub use rendering::{
    CameraTarget, CpuBundleInfo, DebugRender, EguiRender, FlushUploads, ForwardRender, FrameRing,
    FrameTarget, MaterialBundle, MaterialManager, MaterialManagerError, MeshManager, MeshRenderer,
    Primitive, PrimitiveMaterial, RenderPassType, RenderSchedule, ScenePass, TextureManager,
    pack_uniform_bytes, register_rendering_components, shaders,
};

/// Register all standard component types with the world.
///
/// Registers storage, inspector metadata, clone support, and (where
/// applicable) default insertion support. Call this before running
/// systems or using the inspector.
pub fn register_std_components(world: &mut World) {
    // Inspector-enabled components (support "Add Component" via Default)
    world.register_inspector_default::<Transform>();
    world.register_inspector_default::<GlobalTransform>();
    world.register_inspector_default::<Visibility>();
    world.register_inspector_default::<Name>();
    world.register_inspector_default::<DirectionalLight>();
    world.register_inspector_default::<PointLight>();
    world.register_inspector_default::<SpotLight>();

    // Inspector-enabled, readonly (no Default — constructed with parameters)
    world.register_inspector::<Camera>();
    world.register_inspector_default::<FreeFlyCamera>();

    // Hierarchy components (inspector-enabled for clone/remap support)
    world.register_inspector::<Parent>();
    world.register_inspector_default::<Children>();

    // Inspector display order: Name first, then hierarchy, then transforms
    world.set_inspector_order::<Name>(0);
    world.set_inspector_order::<Parent>(10);
    world.set_inspector_order::<Children>(11);
    world.set_inspector_order::<Transform>(20);
    world.set_inspector_order::<GlobalTransform>(21);

    // Required components are now declared via #[require(...)] on the component
    // structs and registered automatically by register_inspector / register_inspector_default.

    // Physics descriptor + handle components (feature-gated)
    #[cfg(any(feature = "physics-3d", feature = "physics-3d-f32"))]
    {
        world.register_inspector_default::<physics::components3d::RigidBody3D>();
        world.register_inspector_default::<physics::components3d::Collider3D>();
        world.register_inspector::<physics::components3d::ImpulseJoint3D>();
        world.register_component::<physics::physics3d::RigidBody3DHandle>();
        world.register_component::<physics::physics3d::ImpulseJoint3DHandle>();
    }
    #[cfg(any(feature = "physics-2d", feature = "physics-2d-f32"))]
    {
        world.register_inspector_default::<physics::components2d::RigidBody2D>();
        world.register_inspector_default::<physics::components2d::Collider2D>();
        world.register_inspector::<physics::components2d::ImpulseJoint2D>();
        world.register_component::<physics::physics2d::RigidBody2DHandle>();
        world.register_component::<physics::physics2d::ImpulseJoint2DHandle>();
    }

    // Rendering components (feature-gated)
    #[cfg(feature = "rendering")]
    {
        rendering::register_rendering_components(world);
    }
}
